force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>Stores car information</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>MUV</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>MSRP</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CarsController.cls
public with sharing class CarsController {
  public class Filters {
    @AuraEnabled
    public String searchInputValue { get; set; }
    @AuraEnabled
    public Decimal carPrice { get; set; }
    @AuraEnabled
    public String[] selectedCategories { get; set; }
    @AuraEnabled
    public String[] selectedBrands { get; set; }
  }

  @AuraEnabled(cacheable=true)
  public static List<Car__c> getCars(Filters filters) {
    System.debug(filters);
    String key, query, whereClause = '';
    Decimal carPrice = 0;
    String[] selectedCategories, selectedBrands, criteria = new List<String>();

    if (filters != null) {
      if (!String.isEmpty(filters.searchInputValue)) {
        key = '%' + filters.searchInputValue + '%';
        criteria.add('Name LIKE :key');
      }
      if (filters.carPrice >= 0) {
        carPrice = filters.carPrice;
        criteria.add('MSRP__c <= :carPrice');
      }
      if (filters.selectedCategories.size() > 0) {
        selectedCategories = filters.selectedCategories;
        criteria.add('Category__c IN :selectedCategories');
      }
      if (filters.selectedBrands.size() > 0) {
        selectedBrands = filters.selectedBrands;
        criteria.add('Brand__c IN :selectedBrands');
      }
      whereClause = ' WHERE ' + String.join(criteria, ' AND ');
    }

    query =
      'SELECT Id, Name, MSRP__c, Picture_URL__c FROM Car__c' +
      whereClause +
      ' WITH SECURITY_ENFORCED ORDER BY Name';

    System.debug(query);
    try {
      return Database.query(query);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Car__c> getSimilarCars(String id, String brand) {
    System.debug(id);
    System.debug(brand);

    try {
      return [
        SELECT Id, Name, MSRP__c, Picture_URL__c
        FROM Car__c
        WHERE Brand__c = :brand AND Id != :id
        LIMIT 2
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}